apiVersion: view.bobuhiro11.net/v1
kind: MarkdownView
metadata:
  labels:
    app.kubernetes.io/name: markdownview
    app.kubernetes.io/instance: markdownview-sample
    app.kubernetes.io/part-of: markdown-view
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: markdown-view
  name: markdownview-sample-noimage
spec:
  markdowns:
    SUMMARY.md: |
      # Summary

      - [Page1](page1.md)
    page1.md: |
      # Page 1

      First page.
  replicas: 1
